### ISSUE TITLE
Problem : type error at reading CSV header

### ISSUE THREAD

**Issue by pywugate** [BoZenKhaa/ReverseGeocode.jl#13]
### Problem : type error at reading CSV header

already defined `COLUMN_TYPE = OrderedDict()` and `header = keys(COLUMN_TYPE)`

in `function download_data(...)`

```julia
julia> data = CSV.File(read(r.files[1]); delim="\t", header, select)
ERROR: TypeError: in keyword argument header, expected Union{Vector{String}, Vector{Symbol}, Integer, AbstractVector{<:Integer}}, 
got a value of type Base.KeySet{Symbol, OrderedDict{Symbol, DataType}}
Stacktrace:
 [1] top-level scope
   @ ~\Documents\Julia\Kaggle\BirdCLEF2023\geoinfo.jl:52
```

it is ok to do this by converting keys into vector.

```julia 
header = collect(keys(COLUMN_TYPE))
julia> data = CSV.File(read(r.files[1]); delim="\t", header, select)
```

(related to [ #12 (comment)](https://github.com/BoZenKhaa/ReverseGeocode.jl/issues/12#issue-2276068440))

**Comment by BoZenKhaa** [comment]
True, I will fix this in the next version, along with #12. Thank you for documenting these issues.
